### PR TITLE
Add new smart contract Multi-tier Referral system

### PR DESCRIPTION
**Pull request by zororaka00**
Addition of ERC721-Based Multi-tier Referral system Smart Contract

In this PR, I have added an ERC721-based Multi-Tier Referral System (MTRS) smart contract. This smart contract allows users to register and become part of the MTRS system using USDC tokens.

The main features of this smart contract are:
- Registration of new users with the determination of an upline.
- Distribution of profits to uplines based on their level in the MTRS system.
- Function to view all token IDs owned by an address.
- Function to view information about the USDC profits received by a token ID.

This smart contract is expected to facilitate transparent and fair MTRS transactions by leveraging blockchain technology.

### CODE REVIEW

**Comment by zxstim** [comment]
Lol. Can you change the name to "Multi-tier Referral system" rather than "MLM"?

**Comment by zororaka00** [comment]
> Multi-tier Referral system

Done for change

**Comment by zxstim** [comment]
Looks good. Let me refresh the bounty category on Dorahacks (https://dorahacks.io/daobounty/438) since it is marked as completed for now. Once it does, just take this merged PR and submit in the bounty category page.

**Comment by zxstim** [comment]
Hi @zororaka00,

I saw you make a submission for complete DApp track (https://dorahacks.io/daobounty/434). 

Can you go to this Issue tab link (https://github.com/klaytn/klaytn-dapp-toolkit/issues/new/choose) and select proposal template and submit a deployed implementation (smart contract plus frontend)?

referral has interesting use case esp. for incentive mechanism

**Comment by zororaka00** [comment]
> and the correct track for this PR has been re-opened. You can submit this merged PR link below.
> 
> https://dorahacks.io/daobounty/446

alright, I submitted it just now

**Pull request merged**
